apiVersion: v1
kind: Secret
metadata:
  name: selectgearmotors-payment-api-secrets
  namespace: selectgearmotors-ns
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  SECURITY_JWT_SECRET_KEY: ${{ secrets.SECURITY_JWT_SECRET_KEY }}
  MERCADO_PAGO_ACCESS_TOKEN_KEY: ${{ secrets.MERCADO_PAGO_ACCESS_TOKEN_KEY }}