apiVersion: v1
kind: Secret
metadata:
  name: selectgearmotors-payment-api-secrets
  namespace: selectgearmotors-ns
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  DATABASE_NAME: "${{ secrets.DATABASE_NAME }}"
  DATABASE_USERNAME: "${{ secrets.DATABASE_USERNAME }}"
  DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
  DATABASE_PORT: "${{ secrets.DATABASE_PORT }}"
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  SECURITY_JWT_SECRET_KEY: "${{ secrets.SECURITY_JWT_SECRET_KEY }}"
  MERCADO_PAGO_ACCESS_TOKEN_KEY: "${{ secrets.MERCADO_PAGO_ACCESS_TOKEN_KEY }}"
  CLIENT_API_URL: "${{ secrets.CLIENT_API_URL }}"
  TRANSACTION_API_URL: "${{ secrets.TRANSACTION_API_URL }}"
  SWAGGER_API_URL: "${{ secrets.SWAGGER_API_URL }}"
  ZIPKIN_URL: "${{ secrets.ZIPKIN_URL }}"
